language: elixir

elixir:
  - 1.10.4

otp_release:
  - 21.3.8.1
  - 23.0.3

env:
  - MIX_ENV=test DB_URL=ecto://postgres:@localhost/ecto_job_test

services:
  - postgresql

cache:
  directories:
    - deps
    - _build

install:
  - mix local.hex --force
  - mix local.rebar --force
  - MIX_ENV=dev mix deps.get

before_script:
  - MIX_ENV=dev mix clean
  - mix do ecto.create, ecto.migrate

script:
  - mix test
  - MIX_ENV=dev mix credo
  - MIX_ENV=dev mix dialyzer

after_script:
  - MIX_ENV=dev mix inch.report
